### ISSUE TITLE
why the number of encoder layers and the number of decoder layers are not equal?

### ISSUE THREAD

**Issue by ConanCui** [mpeychev/disentangled-autoencoders#1]
Mostly, the layes of encoder and decoder should be equal?
However in your code, it shows as below,   

```
encoder_layers_size=[4096, 1200, 1200, 10],
decoder_layers_size=[10, 1200, 1200, 1200, 4096],

```
Could you explain why you set the parameters different?

**Comment by mpeychev** [comment]
There are no restrictions for the encoder and the decoder to have symmetric architectures. In theory, they are even allowed to be arbitrary (and possibly very different) functions.

These particular layer sizes were mostly influenced by the paper of _Higgins et al._ - https://arxiv.org/pdf/1606.05579.pdf, page 10, Appendix A, Table 1. The more layers in the decoder effectively increases its reconstruction ability.
